# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShipAndBox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShipAndBox
  pod 'iOSDropDown', '~> 0.3'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
end
